### ISSUE TITLE
Wrong generation of Polygons for TopSky Maps

### ISSUE THREAD

**Issue by sergej-singer** [VATGER-Nav/mapbuilder#2]
When I tried to generate Topsky Map with `to_poly('name', 'color', 100)`, not forgetting to enter Fill for COORDPOLY tag, I've got every object, which was within one group like this:

> //name
> COLOR:color
> COORD:48.35376529504068:11.79292385590875
> COORD:48.35286980924056:11.79309868550854
> COORD:48.35302036712891:11.79514601311076
> COORD:48.35392379097135:11.7949917077324
> COORD:48.35376529504068:11.79292385590875
> 
> COLOR:color
> COORD:48.35953989377761:11.77799524378658
> COORD:48.35948177647978:11.77809448149061
> COORD:48.3593495733066:11.77813731305117
> COORD:48.35826105813791:11.77829801783823
> COORD:48.35813290003692:11.77823671697916
> COORDPOLY:100

As the COORDPOLY defines every polygon in TopSky, it will draw it like 2 polygons with a thin line between them, which is incorrect. I've implemented a small fix in jinja.py to make sure that COORDPOLY repeats itself just like COLOR:

    def _render_polygon(lines, polygons, color, coordpoly=False):
        for polygon in polygons:
            lines.append(f"COLOR:{color}")

            for point in polygon.coords:
                lines.append(f"COORD:{coord2es((point[0], point[1]))}")
        
            if coordpoly:
                lines.extend((f"COORDPOLY:{coordpoly}", ""))

**Comment by a3li** [comment]
The fix is not correct. Every polygon should be fed to `to_poly` resulting in a corresponding `COORDPOLY` line.
What input data and template causes an issue here?

**Comment by sergej-singer** [comment]
It appeared when I tried to import Buildings from AIXM File, some Buildings contained more than one polygon per Building. But the count of `COORDPOLY` lines was equal to the count of Buildings, not the Polygons themselves. Basically it adds only one `COORDPOLY` line per feature, not per polygon. My fix is correct, because it treats `COORDPOLY` line same as `COLOR` line (which btw doesn't had this problem).

**Comment by sergej-singer** [comment]
Same behavior appeared when I tried to implement MultiGeometries

**Comment by a3li** [comment]
Please provide specific examples, input data and template.

**Comment by sergej-singer** [comment]
Okay, now I've got time to reproduce the mentioned bugs.

What I've had:
The current version of Mapbuilder
[AIXM file of EDLP Groundlayout](https://github.com/user-attachments/files/16247880/EDLP_AerodromeMapping_2024-05-16_2024-05-16_snapshot.zip)

What I wanted:
To generate Building Maps for TopSky (as a test, not as a real map for our sector file)

Here's the .jinja file setup:
```jinja
{% set default = 0.000005 %}
MAP:Buildings
FOLDER:Airport Layout

{% for building, geom in data.edlp['VerticalStructureByName'].items() if building not in ['ANFLUGBEFEUERUNG'] %}
{{ geom | simplify(default) | to_poly(building, 'layout-building', 100) }}
{% endfor %}
````

Here's the resulted Map:
[test.txt](https://github.com/user-attachments/files/16247937/test.txt)

And the first generated building contains the mentioned error:
```
// GLEITWEGSENDER
COLOR:layout-building
COORD:51.6112398268823:8.6057435586576
COORD:51.6112167686801:8.6057662432772
COORD:51.6112355852004:8.6058155845813
COORD:51.611258643412:8.6057928999769
COORD:51.6112398268823:8.6057435586576
COLOR:layout-building
COORD:51.6190369294412:8.6251314746782
COORD:51.6190170846021:8.625081979093
COORD:51.6189945892892:8.6251052546389
COORD:51.6190144341185:8.6251547502099
COORD:51.6190369294412:8.6251314746782
COORDPOLY:100
```
It consist out of 2 Polygons, but there's only one `COORDPOLY` line. The second building, which allegedly was just a point, had also `COORDPOLY` line, which may be a problem, because there's no actual polygons to draw:
```
// WIND DIRECTION INDICATOR
COORDPOLY:100

// TRANSMISSIOMETER
COORDPOLY:100
```

And here's how TopSky drew the map:
![image](https://github.com/user-attachments/assets/a1d1178f-6647-4a06-9c10-c500c8115ad5)

After implementing the aforementioned fix, Mapbuilder adds 'COORDPOLY' line only after each polygon:
[test.txt](https://github.com/user-attachments/files/16248118/test.txt)
```
// GLEITWEGSENDER
COLOR:layout-building
COORD:51.6112398268823:8.6057435586576
COORD:51.6112167686801:8.6057662432772
COORD:51.6112355852004:8.6058155845813
COORD:51.611258643412:8.6057928999769
COORD:51.6112398268823:8.6057435586576
COORDPOLY:100

COLOR:layout-building
COORD:51.6190369294412:8.6251314746782
COORD:51.6190170846021:8.625081979093
COORD:51.6189945892892:8.6251052546389
COORD:51.6190144341185:8.6251547502099
COORD:51.6190369294412:8.6251314746782
COORDPOLY:100
```

Phantom `COORDPOLY` lines are also gone:
```
// WIND DIRECTION INDICATOR

// TRANSMISSIOMETER

```

And here's how TopSky drew it:
![image](https://github.com/user-attachments/assets/8d3d311b-b6bf-4177-959c-2b5195016580)

**Comment by sergej-singer** [comment]
Okay, fair enough, if I had tried to generate Buildings by ID in the AIXM data, and not by Designator, then Mapbuilder would treat every polygon as a separate feature. But still, it wouldn't make sense, if I wanted to generate particular Building by the Designator, which could have been consisted of multiple Polygons.

If I didn't implement this fix, I wouldn't be able to implement MultiGeometries.

**Comment by sergej-singer** [comment]
Maybe you're right, I haven't sent the whole fix, because I forgot to include `to_poly` itself:
```Python
def to_poly(geometries, designator: str, color: str, coordpoly=False):
    lines = [f"// {designator}"] if designator else []

    _render_polygon(lines, _get_geoms(geometries), color, coordpoly)

    return "\n".join(lines)


def _render_polygon(lines, polygons, color, coordpoly=False):
    for polygon in polygons:
        lines.append(f"COLOR:{color}")

        for point in polygon.coords:
            lines.append(f"COORD:{coord2es((point[0], point[1]))}")
        
        if coordpoly:
            lines.append(f"COORDPOLY:{coordpoly}")
```

**Comment by a3li** [comment]
> Okay, fair enough, if I had tried to generate Buildings by ID in the AIXM data, and not by Designator, then Mapbuilder would treat every polygon as a separate feature.

Indeed. `to_poly` is meant to draw one single polygon, never multiple polygons. If you iterate over all buildings anyway, use the regular `VerticalStructure` entry.

> But still, it wouldn't make sense, if I wanted to generate particular Building by the Designator, which could have been consisted of multiple Polygons.

It is currently up to you to make sure you only feed a singular polygon to the function.

**Comment by sergej-singer** [comment]
Okay, can I expect this issue to be fixed, when the multigeometries will get eventually implemented? Or you gonna add new function for that matter?
